version: '3'
services:
  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USERNAME
      POSTGRES_DB: $POSTGRES_DATABASE
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
     - $POSTGRES_PORT:5432
volumes:
  pgdata: