name: Check NextJs build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "v18.17.0"
      - name: Install dependencies
        run: npm ci
      - name: Test
        run: npm run test
